theme: jekyll-theme-minimal
title: ADA data story
description: Success or Failure? Predict the success of your future movie!
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
